# Generated by Django 4.2.8 on 2026-03-07 03:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_trainer', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('focus', models.JSONField(default=list, help_text="List of workout focuses (e.g., ['strength', 'cardio'])")),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('weekly_frequency', models.IntegerField(help_text='Number of workouts per week')),
                ('session_length', models.IntegerField(help_text='Minutes per session')),
                ('is_published', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_plans',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_sessions',
            },
        ),
        migrations.CreateModel(
            name='WorkoutFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_rating', models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')])),
                ('fatigue_level', models.IntegerField(blank=True, help_text='1-5 scale', null=True)),
                ('pain_reported', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.workoutsession')),
            ],
            options={
                'db_table': 'workout_feedback',
            },
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for the schedule', null=True)),
                ('weekly_schedule', models.JSONField(default=dict, help_text="Maps days of week to lists of program section IDs or 'rest'")),
                ('original_weekly_schedule', models.JSONField(blank=True, default=None, help_text='Immutable snapshot of weekly_schedule taken at creation. Used to revert AI adjustments back to the original plan.', null=True)),
                ('is_adjusted', models.BooleanField(default=False, help_text='True if the schedule has been modified by the AI adjustment feature.')),
                ('duration_overrides', models.JSONField(blank=True, default=dict, help_text="Per-day duration overrides in minutes. e.g. {'tuesday': 27}. Set by the shorter_workout recovery option.", null=True)),
                ('focus_overrides', models.JSONField(blank=True, default=dict, help_text="Per-day focus overrides. e.g. {'tuesday': 'mobility'}. Set by the lighter_focus recovery option.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Whether this is the user's active schedule")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programs', models.ManyToManyField(related_name='user_schedules', to='api.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('training_location', models.CharField(choices=[('home', 'Home'), ('gym', 'Gym')], default='home', max_length=20)),
                ('fitness_focus', models.JSONField(default=list, help_text="List of fitness focuses (e.g., ['strength', 'cardio'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('specialty_strength', models.BooleanField(default=False)),
                ('specialty_cardio', models.BooleanField(default=False)),
                ('specialty_flexibility', models.BooleanField(default=False)),
                ('specialty_sports', models.BooleanField(default=False)),
                ('specialty_rehabilitation', models.BooleanField(default=False)),
                ('certifications', models.TextField(blank=True, help_text='Comma-separated certifications', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainer_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(help_text="Day name (e.g., 'Monday', 'Tuesday')", max_length=50)),
                ('type', models.CharField(blank=True, help_text="Optional day description (e.g., 'Upper Body', 'Chest Day')", max_length=100)),
                ('is_rest_day', models.BooleanField(default=False, help_text='Whether this day is a rest day')),
                ('order', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.workoutplan')),
            ],
            options={
                'db_table': 'program_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Exercise instructions/description')),
                ('muscle_groups', models.JSONField(default=list, help_text="List of muscle groups (e.g., ['chest', 'triceps'])")),
                ('exercise_type', models.CharField(choices=[('reps', 'Rep-based'), ('time', 'Time-based')], default='reps', help_text='Whether this exercise is rep-based or time-based', max_length=10)),
                ('default_recommendations', models.CharField(blank=True, help_text="e.g., '3-4 sets of 8-12 reps'", max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='Future: exercise demonstration image', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default exercises are available to all trainers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(blank=True, help_text='If null, this is a default exercise available to all', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, help_text='Time in seconds', null=True)),
                ('rest', models.IntegerField(default=0, help_text='Rest time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.exercise')),
            ],
            options={
                'db_table': 'exercise_sets',
                'ordering': ['set_number'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.programsection'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_session_per_user_per_day'),
        ),
        migrations.AddIndex(
            model_name='userschedule',
            index=models.Index(fields=['user', 'is_active'], name='user_schedu_user_id_a7b5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='programsection',
            index=models.Index(fields=['program', 'order'], name='program_sec_program_434b02_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisetemplate',
            index=models.Index(fields=['trainer', 'is_default'], name='exercise_te_trainer_f52f46_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisetemplate',
            index=models.Index(fields=['name'], name='exercise_te_name_37d2b4_idx'),
        ),
    ]
