# Generated by Django 4.2.8 on 2026-02-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercise_workoutprogram_programsection_exerciseset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='programsection',
            name='program',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
        migrations.DeleteModel(
            name='ProgramSection',
        ),
        migrations.DeleteModel(
            name='WorkoutProgram',
        ),
    ]
