# Generated by Django 4.2.8 on 2026-02-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_multiple_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
