# Generated by Django 4.2.8 on 2026-02-11 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workoutplan_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Exercise instructions/description')),
                ('muscle_groups', models.JSONField(default=list, help_text="List of muscle groups (e.g., ['chest', 'triceps'])")),
                ('exercise_type', models.CharField(choices=[('reps', 'Rep-based'), ('time', 'Time-based')], default='reps', help_text='Whether this exercise is rep-based or time-based', max_length=10)),
                ('default_recommendations', models.CharField(blank=True, help_text="e.g., '3-4 sets of 8-12 reps'", max_length=200)),
                ('image_url', models.URLField(blank=True, help_text='Future: exercise demonstration image', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default exercises are available to all trainers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainer', models.ForeignKey(blank=True, help_text='If null, this is a default exercise available to all', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise_templates',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['trainer', 'is_default'], name='exercise_te_trainer_f52f46_idx'), models.Index(fields=['name'], name='exercise_te_name_37d2b4_idx')],
            },
        ),
    ]
