# Generated by Django 4.2.8 on 2026-02-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_userschedule_program_userschedule_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_session_per_user_per_day'),
        ),
    ]
