# Generated by Django 4.2.8 on 2026-03-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_default_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='duration_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="Per-day duration overrides in minutes. e.g. {'tuesday': 27}. Set by the shorter_workout recovery option.", null=True),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional end date for the schedule', null=True),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='focus_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="Per-day focus overrides. e.g. {'tuesday': 'mobility'}. Set by the lighter_focus recovery option.", null=True),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='is_adjusted',
            field=models.BooleanField(default=False, help_text='True if the schedule has been modified by the AI adjustment feature.'),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='original_weekly_schedule',
            field=models.JSONField(blank=True, default=None, help_text='Immutable snapshot of weekly_schedule taken at creation. Used to revert AI adjustments back to the original plan.', null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workoutplan'),
        ),
    ]
